### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by raphael10-collab** [respondchat/c-go-interop#1]
raphy@raohy:~/marcoCpp$ git clone https://github.com/respondchat/c-go-interop.git
    Cloning into 'c-go-interop'...
    remote: Enumerating objects: 20, done.
    remote: Counting objects: 100% (20/20), done.
    remote: Compressing objects: 100% (15/15), done.
    remote: Total 20 (delta 8), reused 15 (delta 4), pack-reused 0 (from 0)
    Receiving objects: 100% (20/20), done.
    Resolving deltas: 100% (8/8), done.
    raphy@raohy:~/marcoCpp$ cd c-go-interop/
    raphy@raohy:~/marcoCpp/c-go-interop$ go build -buildmode=c-archive -o lib.a lib.go
    go: downloading go1.22.2 (linux/amd64)
    raphy@raohy:~/marcoCpp/c-go-interop$ g++ -Wall main.cpp lib.a -o main && ./main
    sqrt(25.0)=5
    power(5, 3)=125
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6554512027d8]
    
    goroutine 17 [running, locked to thread]:
    main.Request(...)
	    /home/raphy/marcoCpp/c-go-interop/lib.go:28
    Aborted (core dumped)
    raphy@raohy:~/marcoCpp/c-go-interop$ 

OS: Ubuntu 24.04

raphy@raohy:~/marcoCpp/c-go-interop$ gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

**Comment by xnacly** [comment]
Thanks for reporting this issue, i was able to reproduce this bug by following your detailed steps. The main cause was the missing handling of the `error` returned by [`http.Get`](https://pkg.go.dev/net/http#Get):

https://github.com/respondchat/c-go-interop/blob/80802f3d3da2b2514ba0f73bf5285a9056172bfe/lib.go#L27

If the request failed, maybe due to a timeout or a network restriction on the client, a null pointer dereference would occur by returning the [(*Response).StatusCode](https://pkg.go.dev/net/http#Response) field.

#2 fixes this issue.

Thanks again for the bug report :)
